"""Builds capabilities/CATALOG.md directly from the manifest files under
capabilities/_manifests/ — the catalog is a generated view, not a
hand-maintained table, so it can't drift from what the manifests actually
declare.
"""

from datetime import date, datetime, timezone
from pathlib import Path
from typing import Dict, List

CATEGORY_ORDER = ["PLAN", "PROFILE", "DB", "BE", "FE", "TEST", "DOC", "DEVOPS", "SEC", "REF"]

CATEGORY_LABELS = {
    "PLAN": "Planning (PLAN)",
    "PROFILE": "Engineering Profiles (PROFILE)",
    "DB": "Database (DB)",
    "BE": "Backend (BE)",
    "FE": "Frontend (FE)",
    "TEST": "Testing (TEST)",
    "DOC": "Documentation (DOC)",
    "DEVOPS": "Infrastructure (DEVOPS)",
    "SEC": "Security (SEC)",
    "REF": "Refactoring (REF)",
}


def _doc_link(cap_id: str, category: str, docs_dir: Path, manifests_root: Path) -> str:
    """Best-effort: find a procedure doc under capabilities/<category-dir>/
    whose content mentions this capability id, so the catalog links to it
    without requiring a rigid naming convention."""
    category_dir_name = {
        "DB": "database", "BE": "backend", "FE": "frontend", "TEST": "testing",
        "DOC": "documentation", "DEVOPS": "devops", "SEC": "security",
        "REF": "refactoring", "PLAN": "planning", "PROFILE": "profile",
    }.get(category, category.lower())

    category_dir = docs_dir / category_dir_name
    if not category_dir.is_dir():
        return "—"

    for md_file in sorted(category_dir.glob("*.md")):
        try:
            text = md_file.read_text(encoding="utf-8")
        except OSError:
            continue
        if f"# {cap_id}" in text or f"**Manifest:** `{manifests_root.name}/{cap_id}.yaml`" in text:
            rel = md_file.relative_to(docs_dir)
            return f"[{category_dir_name}/{md_file.name}]({rel.as_posix()})"
    return "—"


def build_catalog_markdown(manifests: Dict[str, Dict], docs_root: Path,
                            manifests_root: Path, generated_at: date | None = None) -> str:
    """manifests: {capability_id: raw_manifest_dict}, already schema-valid."""
    generated_at = generated_at or datetime.now(timezone.utc).date()

    by_category: Dict[str, List[Dict]] = {c: [] for c in CATEGORY_ORDER}
    for cap_id, data in manifests.items():
        cap = data["capability"]
        by_category.setdefault(cap["category"], []).append(cap)

    for caps in by_category.values():
        caps.sort(key=lambda c: c["id"])

    lines = [
        "# Capability Catalog — Inventory",
        "",
        "Index of all ACSDD capabilities currently registered in this repository's",
        "`capabilities/` tree. **Generated by `acsdd catalog build` — do not edit by",
        "hand.** Regenerate after adding, versioning, or deprecating a manifest.",
        "",
        f"**Last generated:** {generated_at.isoformat()}",
        "",
    ]

    for category in CATEGORY_ORDER:
        caps = by_category.get(category, [])
        lines.append(f"## {CATEGORY_LABELS[category]}")
        lines.append("")
        if not caps:
            lines.append("*(none yet)*")
            lines.append("")
            continue

        lines.append("| ID | Name | Version | Depends on | Adapter(s) | Manifest | Procedure doc |")
        lines.append("|----|------|---------|------------|------------|----------|----------------|")
        for cap in caps:
            deps = ", ".join(d["capability"] for d in cap.get("dependencies", []) or []) or "—"
            adapters = ", ".join(a["stack"] for a in cap.get("adapters", []) or []) or "—"
            manifest_link = f"[{manifests_root.name}/{cap['id']}.yaml]({manifests_root.name}/{cap['id']}.yaml)"
            doc_link = _doc_link(cap["id"], category, docs_root, manifests_root)
            lines.append(
                f"| {cap['id']} | {cap['name']} | {cap['version']} | {deps} | "
                f"{adapters} | {manifest_link} | {doc_link} |"
            )
        lines.append("")

    # Dependency graph (only for categories/capabilities that have deps or dependents)
    lines.append("## Dependency graph")
    lines.append("")
    lines.append("```")
    roots = [
        cap for caps in by_category.values() for cap in caps
        if not (cap.get("dependencies") or [])
    ]
    dependents: Dict[str, List[str]] = {}
    for caps in by_category.values():
        for cap in caps:
            for dep in cap.get("dependencies", []) or []:
                dependents.setdefault(dep["capability"], []).append(cap["id"])

    printed_any = False
    for root in sorted(roots, key=lambda c: c["id"]):
        children = sorted(dependents.get(root["id"], []))
        if not children:
            continue
        printed_any = True
        lines.append(f"{root['id']} ({root['name']})")
        for i, child_id in enumerate(children):
            connector = "└──" if i == len(children) - 1 else "├──"
            child_name = manifests[child_id]["capability"]["name"] if child_id in manifests else "?"
            lines.append(f"  {connector} {child_id} ({child_name})")
    if not printed_any:
        lines.append("(no dependency edges yet)")
    lines.append("```")
    lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("## Regenerating this file")
    lines.append("")
    lines.append("```bash")
    lines.append("acsdd catalog build")
    lines.append("```")
    lines.append("")
    lines.append(
        "Run `acsdd catalog verify` in CI to fail the build if this file is out of "
        "date relative to the manifests, or if any manifest references a "
        "dependency that doesn't exist / forms a cycle."
    )
    lines.append("")

    return "\n".join(lines)
