"""Builds CATALOG.md directly from the manifest files under the capabilities
tree's _manifests/ — the catalog is a generated view, not a hand-maintained
table, so it can't drift from what the manifests actually declare.

Every path here arrives as an argument (docs_root/manifests_root), and the
rendered markdown never names the tree's location: acsdd keeps it at
.acsdd/capabilities/, but repos onboarded before that move still have a
top-level capabilities/, and a generated file that hardcoded either one would
be wrong in half of them.
"""

from datetime import date, datetime, timezone
from pathlib import Path
from typing import Dict, List

CATEGORY_ORDER = ["PLAN", "PROFILE", "DB", "BE", "FE", "TEST", "DOC", "DEVOPS", "SEC", "REF"]

CATEGORY_LABELS = {
    "PLAN": "Planning (PLAN)",
    "PROFILE": "Engineering Profiles (PROFILE)",
    "DB": "Database (DB)",
    "BE": "Backend (BE)",
    "FE": "Frontend (FE)",
    "TEST": "Testing (TEST)",
    "DOC": "Documentation (DOC)",
    "DEVOPS": "Infrastructure (DEVOPS)",
    "SEC": "Security (SEC)",
    "REF": "Refactoring (REF)",
}


# Where a category's hand-written procedure docs live, relative to the
# capabilities tree's root. Shared with acsdd.capability.generator, which needs
# to know where to scaffold a new doc stub using the same convention.
CATEGORY_DOC_DIR = {
    "DB": "database", "BE": "backend", "FE": "frontend", "TEST": "testing",
    "DOC": "documentation", "DEVOPS": "devops", "SEC": "security",
    "REF": "refactoring", "PLAN": "planning", "PROFILE": "profile",
}


def find_doc_file(cap_id: str, category: str, docs_dir: Path,
                  manifests_root: Path) -> Path | None:
    """Best-effort: the procedure doc under <docs_dir>/<category-dir>/ whose
    content mentions this capability id, or None.

    Matching is on content rather than filename deliberately — docs predate
    the scaffolder and don't all follow its ``<cap-id-lower>.md`` convention.
    Shared with acsdd.capability.remover, which has to find the same file to
    delete it; guessing the filename there would orphan a renamed doc.
    """
    category_dir = docs_dir / CATEGORY_DOC_DIR.get(category, category.lower())
    if not category_dir.is_dir():
        return None

    for md_file in sorted(category_dir.glob("*.md")):
        try:
            text = md_file.read_text(encoding="utf-8")
        except OSError:
            continue
        if f"# {cap_id}" in text or f"**Manifest:** `{manifests_root.name}/{cap_id}.yaml`" in text:
            return md_file
    return None


def _doc_link(cap_id: str, category: str, docs_dir: Path, manifests_root: Path) -> str:
    """The catalog's markdown link to a capability's procedure doc, or an em
    dash when there isn't one."""
    md_file = find_doc_file(cap_id, category, docs_dir, manifests_root)
    if md_file is None:
        return "—"
    rel = md_file.relative_to(docs_dir)
    return f"[{rel.as_posix()}]({rel.as_posix()})"


def build_catalog_markdown(manifests: Dict[str, Dict], docs_root: Path,
                            manifests_root: Path, generated_at: date | None = None) -> str:
    """manifests: {capability_id: raw_manifest_dict}, already schema-valid."""
    generated_at = generated_at or datetime.now(timezone.utc).date()

    by_category: Dict[str, List[Dict]] = {c: [] for c in CATEGORY_ORDER}
    for cap_id, data in manifests.items():
        cap = data["capability"]
        by_category.setdefault(cap["category"], []).append(cap)

    for caps in by_category.values():
        caps.sort(key=lambda c: c["id"])

    lines = [
        "# Capability Catalog — Inventory",
        "",
        "Index of all ACSDD capabilities currently registered in this repository.",
        "**Generated by `acsdd catalog build` — do not edit by hand.** Regenerate",
        "after adding, versioning, or deprecating a manifest.",
        "",
        f"**Last generated:** {generated_at.isoformat()}",
        "",
    ]

    for category in CATEGORY_ORDER:
        caps = by_category.get(category, [])
        lines.append(f"## {CATEGORY_LABELS[category]}")
        lines.append("")
        if not caps:
            lines.append("*(none yet)*")
            lines.append("")
            continue

        lines.append("| ID | Name | Version | Depends on | Adapter(s) | Manifest | Procedure doc |")
        lines.append("|----|------|---------|------------|------------|----------|----------------|")
        for cap in caps:
            deps = ", ".join(d["capability"] for d in cap.get("dependencies", []) or []) or "—"
            adapters = ", ".join(a["stack"] for a in cap.get("adapters", []) or []) or "—"
            manifest_link = f"[{manifests_root.name}/{cap['id']}.yaml]({manifests_root.name}/{cap['id']}.yaml)"
            doc_link = _doc_link(cap["id"], category, docs_root, manifests_root)
            lines.append(
                f"| {cap['id']} | {cap['name']} | {cap['version']} | {deps} | "
                f"{adapters} | {manifest_link} | {doc_link} |"
            )
        lines.append("")

    # Dependency graph (only for categories/capabilities that have deps or dependents)
    lines.append("## Dependency graph")
    lines.append("")
    lines.append("```")
    roots = [
        cap for caps in by_category.values() for cap in caps
        if not (cap.get("dependencies") or [])
    ]
    dependents: Dict[str, List[str]] = {}
    for caps in by_category.values():
        for cap in caps:
            for dep in cap.get("dependencies", []) or []:
                dependents.setdefault(dep["capability"], []).append(cap["id"])

    printed_any = False
    for root in sorted(roots, key=lambda c: c["id"]):
        children = sorted(dependents.get(root["id"], []))
        if not children:
            continue
        printed_any = True
        lines.append(f"{root['id']} ({root['name']})")
        for i, child_id in enumerate(children):
            connector = "└──" if i == len(children) - 1 else "├──"
            child_name = manifests[child_id]["capability"]["name"] if child_id in manifests else "?"
            lines.append(f"  {connector} {child_id} ({child_name})")
    if not printed_any:
        lines.append("(no dependency edges yet)")
    lines.append("```")
    lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("## Regenerating this file")
    lines.append("")
    lines.append("```bash")
    lines.append("acsdd catalog build")
    lines.append("```")
    lines.append("")
    lines.append(
        "Run `acsdd catalog verify` in CI to fail the build if this file is out of "
        "date relative to the manifests, or if any manifest references a "
        "dependency that doesn't exist / forms a cycle."
    )
    lines.append("")

    return "\n".join(lines)
